### ISSUE TITLE
Error uninitialized connection to Elasticsearch

### ISSUE THREAD

**Issue by ctavian** [bitnami/bitnami-docker-fluentd#35]
### Name and Version

1.14.5-debian-10-r5

### What steps will reproduce the bug?

Hello, 

1. Use the following aggregator configuration for ES:

```
    <store>
      @type elasticsearch_dynamic
      include_tag_key true
      host elasticsearch.cluster.local
      port 9200
      suppress_type_name true
      request_timeout 20s
    </store>
 ```

2. Update `1.14.4-debian-10-r11`  to `1.14.5-debian-10-r5`

3. Installing the update with helm is stuck due to a missing package / initialization issue to Elasticsearch.

4. Get log on fluentd aggregator pod.

### What is the expected behavior?

The connection to Elasticsearch is initialized and ready to continue starting the container.

### What do you see instead?

```
/opt/bitnami/fluentd/gems/elasticsearch-xpack-7.17.0/lib/elasticsearch/xpack.rb:43:in `<top (required)>': uninitialized constant Elasticsearch::API::COMMON_PARAMS (NameError)
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:7:in `<top (required)>'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch_dynamic.rb:2:in `require_relative'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch_dynamic.rb:2:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:103:in `block in search'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:100:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:100:in `search'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:44:in `lookup'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:169:in `new_impl'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:114:in `new_output'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:108:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/out_copy.rb:39:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:149:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:665:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
/opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- elasticsearch/xpack (LoadError)
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:7:in `<top (required)>'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch_dynamic.rb:2:in `require_relative'
	from /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch_dynamic.rb:2:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:103:in `block in search'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:100:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:100:in `search'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/registry.rb:44:in `lookup'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:169:in `new_impl'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:114:in `new_output'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:108:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/out_copy.rb:39:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:149:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:665:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

### Additional information

We use the helm bitnami for install and update fluentd.

**Comment by kadzielawa** [comment]
hello @ctavian 

I can see the same behaviour on my release :/ 

looks like that problem is because of some missing ruby gems

https://github.com/uken/fluent-plugin-elasticsearch/issues/944

**Comment by kvokka** [comment]
I made a [PR to fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch/pull/946) which was rejected, but the problem is still in here - the version must be locked.

There is ofc an option to use something like [this](https://github.com/uken/fluent-plugin-elasticsearch/issues/944#issuecomment-1040616890), but it would be great if it'll be possible just to stick with bitnami image.

For now, with bitnami [chart](https://github.com/bitnami/charts/tree/master/bitnami/fluentd) is possible to use this dirty hack, just to make this work for a while (maybe it'll help someone)

```yaml
fluentd:
  forwarder:
    podSecurityContext:
      enabled: true
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    containerSecurityContext:
      enabled: false
    command: ["/bin/sh"]
    args:
      - "-c"
      - |
        /opt/bitnami/scripts/fluentd/setup.sh && \
        gem uninstall -x --ignore-dependencies elasticsearch elasticsearch-api elasticsearch-transport elastic_ruby_console && \
        gem install 'elasticsearch:7.17.0' \
                    'elasticsearch-api:7.17.0' \
                    'elasticsearch-xpack:7.17.0' && \
        /opt/bitnami/scripts/fluentd/entrypoint.sh /opt/bitnami/scripts/fluentd/run.sh
```

**Comment by kvokka** [comment]
gem version bump to `fluent-plugin-elasticsearch:5.2.0` should solve the issue
🎉

**Comment by carrodher** [comment]
Thanks for the info and the workaround, the issue should be solved once released a new version of this image with the latest plugin, right?

**Comment by ctavian** [comment]
Hello @kvokka, I'm waiting for the bitnami side PR to be ready so I can confirm it works

**Comment by kvokka** [comment]
The latest image `1.14.5-debian-10-r10` does not contain these changes atm

**Comment by fvogl** [comment]
> ```yaml
> containerSecurityContext:
>       enabled: false
> ```

wanted to use this hack to get my ES 7.16.3 supported but getting:
You don't have write permissions for the /opt/bitnami/fluentd/bin directory.

**Comment by fvogl** [comment]
wanted to use this but getting "You don't have write permissions for the /opt/bitnami/fluentd/bin directory. "



> I made a [PR to fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch/pull/946) which was rejected, but the problem is still in here - the version must be locked.
> 
> There is ofc an option to use something like [this](https://github.com/uken/fluent-plugin-elasticsearch/issues/944#issuecomment-1040616890), but it would be great if it'll be possible just to stick with bitnami image.
> 
> For now, with bitnami [chart](https://github.com/bitnami/charts/tree/master/bitnami/fluentd) is possible to use this dirty hack, just to make this work for a while (maybe it'll help someone)
> 
> ```yaml
> fluentd:
>   forwarder:
>     podSecurityContext:
>       enabled: true
>       runAsUser: 0
>       runAsGroup: 0
>       fsGroup: 0
>     containerSecurityContext:
>       enabled: false
>     command: ["/bin/sh"]
>     args:
>       - "-c"
>       - |
>         /opt/bitnami/scripts/fluentd/setup.sh && \
>         gem uninstall -x --ignore-dependencies elasticsearch elasticsearch-api elasticsearch-transport elastic_ruby_console && \
>         gem install 'elasticsearch:7.17.0' \
>                     'elasticsearch-api:7.17.0' \
>                     'elasticsearch-xpack:7.17.0' && \
>         /opt/bitnami/scripts/fluentd/entrypoint.sh /opt/bitnami/scripts/fluentd/run.sh
> ```

**Comment by kvokka** [comment]
Do you forwarders use elasticsearch? It's an aggregator responsibility (i do not even have this hack for forwarders)

**Comment by fvogl** [comment]
> Do you forwarders use elasticsearch? It's an aggregator responsibility (i do not even have this hack for forwarders)

Yes, I tried this on the aggregator side. I've now put these gem operations in a custom docker image extending the one from here, so my issue is solved, but if the hack would work it would be better indeed.
