### ISSUE TITLE
Error loading fluent-plugin-detect-exceptions-0.0.14

### ISSUE THREAD

**Issue by irizzant** [bitnami/bitnami-docker-fluentd#38]
### Name and Version

bitnami/fluentd:1.14.6-debian-10-r1

### What steps will reproduce the bug?

1. run the image and use the[ fluent-plugin-detect-exceptions](https://www.rubydoc.info/gems/fluent-plugin-detect-exceptions/0.0.14)
```
<match **>
  @type detect_exceptions
  remove_tag_prefix foo
  message log
  languages java, python
  multiline_flush_interval 0.1
</match>
```
2. See the following error:
```
fluentd 11:24:26.36 INFO  ==> ** Starting Fluentd **
2022-04-13 11:24:26 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2022-04-13 11:24:27 +0000 [info]: gem 'fluentd' version '1.14.6'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.14'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.2.1'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-grafana-loki' version '1.2.18'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-kafka' version '0.17.5'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.5'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.2'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-s3' version '1.6.1'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
/opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- /opt/bitnami/fluentd/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/out_detect_exceptions (LoadError)
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:103:in `block in search'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:100:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:100:in `search'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:44:in `lookup'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/plugin.rb:169:in `new_impl'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/plugin.rb:114:in `new_output'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:130:in `add_match'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:74:in `block in configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/label.rb:31:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `block in configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:105:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:80:in `run_configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:668:in `run_supervisor'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/command/fluentd.rb:356:in `<top (required)>'
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/bin/fluentd:15:in `<top (required)>'
        from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
        from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

### What is the expected behavior?

Fluentd should load the configuration and start without errors

### What do you see instead?

Fluentd gives the error
```
fluentd 11:24:26.36 INFO  ==> ** Starting Fluentd **
2022-04-13 11:24:26 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2022-04-13 11:24:27 +0000 [info]: gem 'fluentd' version '1.14.6'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.14'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.2.1'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-grafana-loki' version '1.2.18'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-kafka' version '0.17.5'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.5'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.2'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-s3' version '1.6.1'
2022-04-13 11:24:27 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
/opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- /opt/bitnami/fluentd/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/out_detect_exceptions (LoadError)
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:103:in `block in search'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:100:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:100:in `search'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/registry.rb:44:in `lookup'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/plugin.rb:169:in `new_impl'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/plugin.rb:114:in `new_output'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:130:in `add_match'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:74:in `block in configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/label.rb:31:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `block in configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `each'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:105:in `configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:80:in `run_configure'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:668:in `run_supervisor'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/command/fluentd.rb:356:in `<top (required)>'
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/bitnami/fluentd/gems/fluentd-1.14.6/bin/fluentd:15:in `<top (required)>'
        from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
        from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

**Comment by javsalgar** [comment]
Hi,

Could you share with us a values.yaml that triggers the issue? I tried reproducing it but saw something different:

```
2022-04-18 08:44:30 +0000 [warn]: #0 emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/opt/bitnami/fluentd/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/out_detect_exceptions.rb:137:in `synchronize'" tag="kubernetes.var.log.containers.cilium-qbqh5_kube-system_cilium-agent-f3f725f3e8f41952a44f256e6b186f07573e94bd08fa476970e2550ac7435908.log"
```

It seems it's different in my case.

**Comment by irizzant** [comment]
Hi @javsalgar 
you can try with this
```yaml
  
forwarder:
  enabled: false
  
aggregator:
  replicaCount: 2
  
  persistence:
    enabled: true
 
  configMapFiles:
    fluentd-output.conf: |
    fluentd-inputs.conf: |
    metrics.conf: |  
    
    fluentd.conf: |-
      # HTTP input for the liveness and readiness probes
      <source>
        @type http
        bind 0.0.0.0
        port 9880
      </source>
      
      @include /opt/bitnami/fluentd/conf/custom*.conf
      
      # Gestione log fluentd
      
      <match fluentd.healthcheck>
      	@type null
      </match>
      
      <label @FLUENT_LOG>
        <match **>
          @type null
          @id ignore_fluent_logs
        </match>
      </label>
      
    custom_source.conf: |-
      # TCP input to receive logs from
      <source>
        @type forward
        bind 0.0.0.0
        port 24224
        @label @KUBERNETES
      </source>
    
    custom_monitoring.conf: |-
      # Prometheus Exporter Plugin
      # input plugin that exports metrics
      <source>
        @id prometheus
        @type prometheus
      </source>
      
      <source>
        @id monitor_agent
        @type monitor_agent
      </source>
      
      # input plugin that collects metrics from MonitorAgent
      <source>
        @id prometheus_monitor
        @type prometheus_monitor
        <labels>
          host ${hostname}
        </labels>
      </source>
      
      # input plugin that collects metrics for output plugin
      <source>
        @id prometheus_output_monitor
        @type prometheus_output_monitor
        <labels>
          host ${hostname}
        </labels>
      </source>
           
    custom_filters.conf: |-
      <label @KUBERNETES>
        
        ## Detect exceptions in the log output and forward them as one log entry.
        <match **>
          @type detect_exceptions
          remove_tag_prefix raw
          message log
          languages java, python
          multiline_flush_interval 0.1
          max_bytes 500000
          max_lines 1000
        </match>
        
        <match fluentd.healthcheck>
      	  @type null
        </match>
        
        <filter **>
          @id filter_exceptions
          @type concat
          key log
          multiline_start_regexp /^\d{8}_\d{6}_\d{3}.*\#\[\[/
          timeout_label @DISPATCH
          flush_interval 1
        </filter>
        
        <match kubernetes.var.log.containers.fluentd**>
          @type relabel
          @label @FLUENT_LOG
        </match>
        
        <match **>
          @type relabel
          @label @DISPATCH
        </match>
      </label>
    
    custom_dispatch.conf: |-
      <label @DISPATCH>
        <filter **>
          @type prometheus
          <metric>
            name fluentd_input_status_num_records_total
            type counter
            desc The total number of incoming records
            <labels>
              tag ${tag}
              hostname ${hostname}
            </labels>
          </metric>
        </filter>
        
        <match **>
          @type relabel
          @label @OUTPUT
        </match>
      </label>
    
    custom_outputs.conf: |-
      <label @OUTPUT>
        <match **>
           @type loki
           url "http://loki-loki-simple-scalable-gateway.loki.svc.cluster.local"
           remove_keys namespace_name,pod_name,host
           drop_single_key true
           <label>
             container container_name
             pod pod_name
             namespace namespace_name
             host host
           </label>
           <buffer>
             @type file
             path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        	 flush_thread_count 4
        	 flush_interval 5s
           </buffer>      
        </match>
      </label>
```

**Comment by rafariossaa** [comment]
Hi,
  I think this issue is related to this one https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/issues/31

Other plugins seems to have permission for `others` to execute

```
I have no name!@e5ceb7ad83e3:$ ls -l /opt/bitnami/fluentd/gems/fluent-plugin-multi-format-parser-1.0.0/lib/fluent/plugin
total 4
-rw-rw-r-- 1 root root 911 Mar 31 06:18 parser_multi_format.rb
I have no name!@e5ceb7ad83e3:$ ls -l /opt/bitnami/fluentd/gems/fluent-plugin-grafana-loki-1.2.18/lib/fluent/plugin
total 16
-rw-rw-r-- 1 root root 12420 Mar 31 06:16 out_loki.rb
I have no name!@e5ceb7ad83e3:$ ls -l /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.9.5/lib/fluent/plugin
total 60
-rw-rw-r-- 1 root root 18827 Mar 31 06:17 filter_kubernetes_metadata.rb
-rw-rw-r-- 1 root root  3987 Mar 31 06:17 kubernetes_metadata_cache_strategy.rb
-rw-rw-r-- 1 root root  4638 Mar 31 06:17 kubernetes_metadata_common.rb
-rw-rw-r-- 1 root root  1171 Mar 31 06:17 kubernetes_metadata_stats.rb
-rw-rw-r-- 1 root root  1725 Mar 31 06:17 kubernetes_metadata_test_api_adapter.rb
-rw-rw-r-- 1 root root  1699 Mar 31 06:17 kubernetes_metadata_util.rb
-rw-rw-r-- 1 root root  6502 Mar 31 06:17 kubernetes_metadata_watch_namespaces.rb
-rw-rw-r-- 1 root root  7028 Mar 31 06:17 kubernetes_metadata_watch_pods.rb
```

but not in the case of  `fluentd-plugin-detect-exceptions`

```
I have no name!@e5ceb7ad83e3:$ ls -l /opt/bitnami/fluentd/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/
total 24
-rw-rw---- 1 root root 12916 Mar 31 06:16 exception_detector.rb
-rw-rw---- 1 root root  4614 Mar 31 06:16 out_detect_exceptions.rb
```

**Comment by irizzant** [comment]
activity!

**Comment by irizzant** [comment]
Guys I don't know what happened here really, but I've just tried again and now it works, adding a simple reproducer
[reproducer.tar.gz](https://github.com/bitnami/bitnami-docker-fluentd/files/8676009/reproducer.tar.gz)
.
